# Standard Library


In [7]:
## command query separation principle
# asking a question should not change the answer

# command methods perform a task
# example wb.create_sheet()

# a query should not execute any actions
import openpyxl

wb = openpyxl.load_workbook("transactions.xlsx")
sheet = wb["Sheet1"]

for row in range(1, 10):
    # te following line will query and write
    # this will result in empty lines
    cell = sheet.cell(row, 1)
    print(cell.value)
sheet.append([1, 2, 3])
wb.save("transcations2.xlsx")


transaction_id
1001
1002
1003
None
None
None
None
None


In [9]:
## numpy
import numpy as np 

# create numpy array
array = np.array([1, 2, 3])

print(array)
print(type(array))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
# create numpy matrix
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array)
print(type(array))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
# shape attribute
print(array.shape)

In [13]:
## np.zeros

# create matrix with shpae
# default is floating point
array = np.zeros((3, 4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
## create matrix with integers
array = np.zeros((3, 4), dtype=int)
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
## np.ones
# fills with ones
array = np.ones((3, 4), dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
# fill with specific number
array = np.full((3, 4), 5, dtype=int)
print(array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
# fill with random number
# fill with any number
array = np.random.random((3, 4))
print(array)

[[0.25665642 0.98635676 0.18266354 0.52958051]
 [0.86544724 0.90249787 0.63530768 0.54442955]
 [0.27570383 0.21080856 0.55920658 0.81299301]]


In [21]:
# get first row and first column
array = np.random.random((3, 4))
print(array)
print(array[0, 0])

[[0.14288493 0.72033077 0.87595886 0.3111547 ]
 [0.44688301 0.5767144  0.75305883 0.90619566]
 [0.84631106 0.98300115 0.7195851  0.0829497 ]]
0.14288493263957813


In [22]:
# evaluate every element against condition
print(array > 0.2)

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]]


In [23]:
# evaluate boolean expression
# creates an array with only the elements that match the condition
print(array[array > 0.2])

[0.72033077 0.87595886 0.3111547  0.44688301 0.5767144  0.75305883
 0.90619566 0.84631106 0.98300115 0.7195851 ]


In [24]:
# array sum
print(np.sum(array))

7.365028181633946


In [26]:
# array floor and ceiling
# gets the floor of each element
print(np.floor(array))
print(np.ceil(array))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# round
print(np.round(array))

[[0. 1. 1. 0.]
 [0. 1. 1. 1.]
 [1. 1. 1. 0.]]


In [29]:
# arithmetic operations
first = np.array([1, 2, 3])
second = np.array([1, 2, 3])
print(first + second)
print(first + 2)

[2 4 6]
[3 4 5]


In [30]:
# multiplication
print(first * second)

[1 4 9]


In [32]:
dimensions_inch = np.array([1, 2, 3])
dimensions_cm = dimensions_inch * 2.54
print(dimensions_cm)

[2.54 5.08 7.62]
