In [2]:
import numpy as np

# create array
array = np.array([1, 2, 3])
print(type(array))
print(array)

[1 2 3]


In [5]:
# create matrix
array = np.array([[1, 2, 3], [4, 5, 6]])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [6]:
# see shape
print(array.shape)

(2, 3)


In [7]:
# create matrix with zeros m- the default data type is float
array = np.zeros((3, 4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# create matrix with integers
array = np.zeros((3, 4), dtype=int)
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
# create matrix with integers that are ones
array = np.ones((3, 4), dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
# create matrix with integers that are a specific number
array = np.full((3, 4), 5, dtype=int)
print(array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [12]:
# create matrix with random numbers
array = np.random.random((3, 4))
print(array)

[[0.62597512 0.00176087 0.05417097 0.9052126 ]
 [0.68331941 0.07088444 0.70975655 0.50864541]
 [0.475773   0.97224914 0.48595719 0.41317969]]


In [13]:
# get elements by index
print(array[0, 0])

0.625975123196381


In [14]:
# show if numbers that are > 0.2 in array
print(array > 0.2)

[[ True False False  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [15]:
# show the numbers that are > 0.2 in array
print(array[array > 0.2])

[0.62597512 0.9052126  0.68331941 0.70975655 0.50864541 0.475773
 0.97224914 0.48595719 0.41317969]


In [16]:
# print sum of elements in the array
print(np.sum(array))

5.906884388223061


In [17]:
# print the floor for each element in the array
print(np.floor(array))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# print the ceiling for each  element in the array
print(np.ceil(array))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# print the rounded value of element in the array
print(np.round(array))

[[1. 0. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 0. 0.]]


In [21]:
# add arrays
first = np.array([1, 2, 3])
second = np.array([1, 2, 3])
print(first + second)

[2 4 6]


In [22]:
# subtract arrays
print(first - second)

[0 0 0]


In [23]:
# multiply arrays
print(first * second)

[1 4 9]


In [24]:
# divide arrays
print(first / second)

[1. 1. 1.]


In [25]:
# add constant to every element of array
print(first + 2)

[3 4 5]


In [26]:
# convert all elements to centimiters
dimensions_inch = np.array([1, 2, 3])
dimensions_cm = dimensions_inch * 2.54
print(dimensions_cm)

[2.54 5.08 7.62]
